ALTER TABLE app_role ADD COLUMN creation_time TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE app_role ADD COLUMN modified_time TIMESTAMP NULL;
ALTER TABLE app_role ADD COLUMN modified_by VARCHAR(45) NOT NULL DEFAULT '';
